ALTER TABLE utilisateur
	MODIFY COLUMN statut ENUM('PENDING','ACTIVE','INACTIVE','LOCKED') NOT NULL DEFAULT 'ACTIVE',
	ADD COLUMN IF NOT EXISTS indicatif_pays VARCHAR(5) DEFAULT NULL AFTER telephone,
	ADD COLUMN IF NOT EXISTS telephone_verifie TINYINT(1) NOT NULL DEFAULT 0 AFTER indicatif_pays;

ALTER TABLE agence
	ADD COLUMN IF NOT EXISTS indicatif_pays VARCHAR(5) DEFAULT NULL AFTER telephone;

ALTER TABLE locataire
	ADD COLUMN IF NOT EXISTS indicatif_pays VARCHAR(5) DEFAULT NULL AFTER telephone;

ALTER TABLE proprietaire
	ADD COLUMN IF NOT EXISTS indicatif_pays VARCHAR(5) DEFAULT NULL AFTER telephone;

CREATE TABLE IF NOT EXISTS otp_code (
	id_otp BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	id_utilisateur BIGINT(20) UNSIGNED NOT NULL,
	objectif ENUM('PHONE_VERIFICATION') NOT NULL DEFAULT 'PHONE_VERIFICATION',
	code_hash CHAR(64) NOT NULL,
	tentatives TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
	tentatives_max TINYINT(3) UNSIGNED NOT NULL DEFAULT 5,
	statut ENUM('PENDING','VERIFIED','EXPIRED','FAILED') NOT NULL DEFAULT 'PENDING',
	date_expiration DATETIME NOT NULL,
	date_verification DATETIME DEFAULT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_otp),
	KEY idx_otp_code_utilisateur (id_utilisateur, statut),
	CONSTRAINT fk_otp_code_utilisateur FOREIGN KEY (id_utilisateur)
		REFERENCES utilisateur (id_utilisateur) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
